name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: ['3.4.10','3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U flake8
          pip install -U isort
          pip install -U yapf
      - name: Run linter and pytest
        run: |
          find . -not -path '*/.eggs/*' -not -path './venv/*' -name '*.py' | xargs flake8 
          python manage.py test
